import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
 
// Font files can be colocated inside of `pages`
// const myFont = localFont({ src: './font/FuturaPT-bold.woff2' })
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const roboto = localFont({
//   src: [
//     {
//       path: './font/FuturaPT-medium.woff2',
//       weight: '400',
//       style: 'normal',
//     },

//     {
//       path: './font/FuturaPT-bold.woff2',
//       weight: '700',
//       style: 'normal',
//     },
//     // {
//     //   path: './font/Roboto-BoldItalic.ttf',
//     //   weight: '700',
//     //   style: 'italic',
//     // },
//   ],
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
